# Generated by Django 2.2 on 2019-04-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGroup',
            fields=[
                ('player_group', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='group',
        ),
        migrations.AddField(
            model_name='player',
            name='player_group',
            field=models.ForeignKey(default=123456, on_delete=django.db.models.deletion.CASCADE, to='quiz.PlayerGroup'),
            preserve_default=False,
        ),
    ]
