# Generated by Django 2.2 on 2019-04-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_player_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='session_id',
        ),
    ]
