# Generated by Django 2.2 on 2019-04-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('group', models.IntegerField(db_index=True)),
                ('score', models.IntegerField(default=0)),
                ('lives', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('choice_1', models.TextField(max_length=300)),
                ('valid_1', models.TextField(max_length=300)),
                ('choice_2', models.TextField(max_length=300)),
                ('valid_2', models.TextField(max_length=300)),
                ('choice_3', models.TextField(max_length=300)),
                ('valid_3', models.TextField(max_length=300)),
                ('choice_4', models.TextField(max_length=300)),
                ('valid_4', models.TextField(max_length=300)),
            ],
        ),
    ]
