# Generated by Django 2.2 on 2019-04-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='valid_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_3',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='valid_4',
            field=models.BooleanField(),
        ),
    ]
